# Ativa o perfil de desenvolvimento
spring.profiles.active=dev

# Configurações do Banco (Copiadas do seu arquivo de teste, mas ajustadas)
spring.datasource.url=jdbc:mysql://localhost:3306/api_test
spring.datasource.username=root
spring.datasource.password=manbo
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA - Mudei para update para você não perder os dados toda hora
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Configurações para GMAIL
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=pedronahum90@gmail.com
spring.mail.password= # COLOQUE SUA SENHA DE APP AQUI (NÃO COMITAR)
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true


# 1. Define o caminho e nome do arquivo (A pasta 'logs' será criada na raiz)
logging.file.name=logs/app.log

# 2. Define o nível de log para o SEU pacote (ajuste com o nome do seu pacote)
# Use DEBUG para ver tudo ou INFO para ver apenas o principal
logging.level.com.pedro.api=DEBUG

# 3. Opcional: Define o nível para o Hibernate (se quiser ver o SQL no arquivo de log)
logging.level.org.hibernate.SQL=DEBUG

# ---- SPRING SECURITY OAUTH2 JWT CONFIG ----

# O ID e Secret da sua aplicação (O Postman vai precisar disso para gerar o token)
security.client-id=myclientid
security.client-secret=myclientsecret

# Tempo de duração do Token JWT em segundos (Ex: 86400 = 24 horas)
security.jwt.duration=86400

# CORS: Quais domínios podem acessar a sua API? (O * significa que todos podem)
cors.origins=http://localhost:3000,http://localhost:5173