# Configurações do Banco para Testes
spring.datasource.url=jdbc:mysql://localhost:3306/api_test?createDatabaseIfNotExist=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=manbo
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Reseta o banco a cada bateria de testes
spring.jpa.hibernate.ddl-auto=create-drop

# Configurações de LOG para Testes
logging.file.name=logs/app-test.log
logging.level.com.pedro.api=DEBUG
logging.level.org.hibernate.SQL=DEBUG

# CONFIGURAÇÕES DE SEGURANÇA PARA TESTES
security.client-id=myclientid
security.client-secret=myclientsecret
security.jwt.duration=86400
cors.origins=http://localhost:3000,http://localhost:5173