# 1. Define o caminho e nome do arquivo (A pasta 'logs' será criada na raiz)
logging.file.name=logs/app.log

# 2. Define o nível de log para o SEU pacote (ajuste com o nome do seu pacote)
# Use DEBUG para ver tudo ou INFO para ver apenas o principal
logging.level.com.pedro.api=DEBUG

# 3. Opcional: Define o nível para o Hibernate (se quiser ver o SQL no arquivo de log)
logging.level.org.hibernate.SQL=DEBUG

# Mantenha as configurações do Gmail que fizemos agora:
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=pedronahum90@gmail.com
spring.mail.password=pgityolouezehluv
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# ADICIONE ESTAS LINHAS para satisfazer o ServiceConfig da aula passada:
notificador.email.host=smtp.gmail.com
notificador.email.port=587